pipeline:
  identifier: Build_exafire_dev_demo_calculator_1727002703817
  name: Build demo-calculator
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1727001367615
        repoName: exafire-dev/demo-calculator
  stages:
    - stage:
        identifier: build1
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: BuildAndPushECR
                  name: BuildAndPushECR
                  identifier: BuildAndPushECR
                  spec:
                    connectorRef: exafireaws
                    region: eu-south-2
                    account: "157586051329"
                    imageName: calculator-demo
                    tags: <+input>
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.exafireekscluster
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
        type: CI
        description: ""
